name: CI
on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  typecheck:
    runs-on: ubuntu-latest
    name: Typecheck

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          run_install: true

      - name: Check typechecking
        run: pnpm typecheck
